### PR TITLE
Add a new paper 

### PR DESCRIPTION
**Pull request by jeremi**
'Providing Decentralized Identity to the most vulnerable populations'

### CODE REVIEW

**Comment by ChristopherA** [comment]
Merged, but can you make sure there is a simple link in topics README

**Comment by ChristopherA** [comment]
Oops, there is a merge conflict. Can you resolve?

**Comment by jeremi** [comment]
@ChristopherA I resolved the merge issue.
I fixed the indentation of 2 other projects in the Readme.md at the same time

**Comment by ChristopherA** [comment]
Thank you!

**Pull request merged**
