### PR TITLE
Update rightsframeworks.md

### PR DESCRIPTION
**Pull request by hackylawyER**

### CODE REVIEW

**Comment by jandrieu** [comment]
Btw, I think you have the power to edit directly and to merge your own pull requests if you prefer that method. For small changes, you can use github's built-in editor.

**Comment by ChristopherA** [comment]
I did add @hackylawyER as a collaborator, so she can now direct add and edit documents in this repo. The general convention is that you can add or edit your own documents using web interface or directly push a commit to master branch, including the README.md files, but to use PRs (pull requests) for changes to collaborative files or files of others. This can also be done through web interface but is harder.

**Comment by hackylawyER** [comment]
Yeah sorry I don't have the client on my Mac.

**Comment by ChristopherA** [comment]
Now that you have collaborator status you can also do it all in web-only interface :-)

**Comment by hackylawyER** [comment]
Fancy :)

**Pull request merged**
