### PR TITLE
Zero-knowledge Proofs on identity systems: Paper submission

### PR DESCRIPTION
**Pull request by davidsrz**

### CODE REVIEW

**Comment by jandrieu** [comment]
David, 

The paper looks good, but we have merge conflicts on the readme. Could you fix?

**Comment by davidsrz** [comment]
Hi, I'm not able to resolve the conflicts now. The README.md file has been deleted

Thanks

**Comment by shannona** [comment]
Did it from the command line on my clone; should all be there now.

**Comment by davidsrz** [comment]
Thanks!

**Pull request closed without merging**
