### PR TITLE
Create Aligning-SSI-with-European-Union-Identity-legislation-eIDAS.md

### PR DESCRIPTION
**Pull request by nalamillo**
This paper aims to advance the alignment of SSI solutions with the eIDAS Regulation regarding electronic identification. We'd like to progress it to a collaborative effort

### CODE REVIEW

**Comment by ChristopherA** [comment]
Can you please add abstract and links to your paper to the /README.md and /topics-and-advance-readings/README.md. Thanks.

**Comment by nalamillo** [comment]
Yes, thanks.

Nacho Alamillo Domingo
Advocat, PhD, CISA, CISM, COBIT 5-f, ITIL V3-f
Director
Astrea La Infopista Jurídica S.L.
Passeig Prim, 25A, 6è, 1a, 43202, Reus
Telf: +34 977 345 405. Mob: +34 663 087 606
Skype: nacho.alamillo
https://es.linkedin.com/in/nachoalamillo


Advertiment legal: la informació d’aquest missatge de correu electrònic és confidencial i s’adreça exclusivament al destinatari previst. Si ha rebut el missatge per error, sisplau, notifiqui-ho a http://contact.astrea.cat<http://contact.astrea.cat/> , i esborri’l sense copiar-lo, enregistrar-lo, ni distribuir-lo.



Advertencia legal: la información de este mensaje de correo electrónico es confidencial y se dirige exclusivamente al destinatario previsto. Si ha recibido el mensaje por error, por favor, notifíquelo a http://contact.astrea.es<http://contact.astrea.es/> , y bórrelo sin copiarlo, grabarlo, ni distribuirlo.




De: Christopher Allen <notifications@github.com>
Enviado el: viernes, 8 de febrero de 2019 20:36
Para: WebOfTrustInfo/rwot8-barcelona <rwot8-barcelona@noreply.github.com>
CC: Nacho Alamillo <nacho@astrea.cat>; Author <author@noreply.github.com>
Asunto: Re: [WebOfTrustInfo/rwot8-barcelona] Create Aligning-SSI-with-European-Union-Identity-legislation-eIDAS.md (#57)


Can you please add abstract and links to your paper to the /README.md and /topics-and-advance-readings/README.md. Thanks.

**Comment by nalamillo** [comment]
Sorry, I'm new to GitHub and I'm unsure how to do it...

**Comment by nalamillo** [comment]
I think I've done it. Please can you check? Thanks, Nacho

**Comment by nalamillo** [comment]
I think I did something wrong, because the .md file is not accessible, Sorry...

**Comment by shannona** [comment]
@nalamillo your pull request was a blank file. I'd suggest trying again, which you should now be able to do by modifying your file: https://github.com/WebOfTrustInfo/rwot8-barcelona/blob/master/topics-and-advance-readings/Aligning-SSI-with-European-Union-Identity-legislation-eIDAS.md

**Comment by nalamillo** [comment]
Please check if it's fixed now. Thanks

**Pull request merged**
