### PR TITLE
Rights Frameworks

### PR DESCRIPTION
**Pull request by hackylawyER**
Adding a topic paper on rights frameworks.

### CODE REVIEW

**Comment by jandrieu** [comment]
Content looks good. Could you add a title and byline to the paper itself? Preferably with contact info (or Twitter/LinkedIn handle if you prefer that).

**Comment by ChristopherA** [comment]
Merged but need author contact information and update to the two readmes. I’ll add you as a contributor for this repo so you can directly edit.

**Comment by hackylawyER** [comment]
Cool thanks!

**Comment by hackylawyER** [comment]
Thanks, I amended my paper and edited the README as well.

Thanks again!

**Pull request merged**
