### PR TITLE
Added README updates (and fixed a markdown error in the paper)

### PR DESCRIPTION
**Pull request by mavarley**

### CODE REVIEW

**Comment by mavarley** [comment]
Oops, this commit has conflicts... let me know if you want me to resolve them and try again.

**Comment by ChristopherA** [comment]
@mavarley There is still is a merge conflict. Do you need help resolving?

**Comment by mavarley** [comment]
alright, should be all good now. Thanks

**Comment by jandrieu** [comment]
Sorry. I just introduced some more merge conflicts, I pulled in some fixes from other PRs.

Could you review and see that we have all the titles in the new structure?

**Pull request merged**
