### PR TITLE
Create The-Untimely-Death-Of-SSI

### PR DESCRIPTION
**Pull request by mxshea**
Submission for RWOT.

### CODE REVIEW

**Comment by peacekeeper** [comment]
Shortest topic paper in the history of RWoT? :)

**Comment by mxshea** [comment]
In reviewing the breadth and depth of the topic’s being suggested here (on RWOT) and participating in a learning mode on various VC calls, Zoom calls and Rocket Chat channels, it is very evident that the identity community is a very tight and active group.  The levels of participation and engagement are high, but it is small; and thoughts, concepts and opinions do risk an echo chamber reinforcement effect.  

The recent experience around the application to the W3C for DID WG status around the state of the Use Case documentation, suggests that it might be useful to take a step back and reflect on what where the the RWOT/SSI community may not being seeing the full landscape and the result would be to ‘miss the wave’ that appears to be forming under identity.

The proposal of this topic is to do a Strength, Weakness, Opportunities and Threat (SWOT) analysis around the space at large, to surface any areas that need attention, and come up with ideas and approaches in order to reduce the risk of surprise and having the market be coopted or move off in another direction.

The goal is to avoid the famous Maxwell Smart quote: https://www.youtube.com/watch?v=oPwrodxghrw

P.S.  Hopefully, I did not screw this submission up again...

**Comment by ChristopherA** [comment]
I've not merged this as it needs addition of abstract to /README.md & add link to topics dir README.md

**Comment by mxshea** [comment]
Hi Chris,

Sorry, I got swamped with a bunch of work. I will get this done tomorrow.  

Michael S.

**Pull request merged**
