### PR TITLE
Topic paper for decentralized code signing based on updated 2015 topic paper

### PR DESCRIPTION
**Pull request by msgilligan**
I'm just starting work on this, so not ready to merge.

If anyone has any suggestions or wants to help, please let me know.

### CODE REVIEW

**Comment by ChristopherA** [comment]
You ready to merge yet?

**Comment by ChristopherA** [comment]
??

**Comment by msgilligan** [comment]
OK, this topic paper is ready for review and/or merging!

**Comment by ChristopherA** [comment]
Thanks!

**Pull request merged**
