### PR TITLE
Create Applying POLA to User Interaction.md

### PR DESCRIPTION
**Pull request by btulloh**

### CODE REVIEW

**Comment by btulloh** [comment]
added paper

**Comment by btulloh** [comment]
Done.

**Comment by ChristopherA** [comment]
Thanks!

**Comment by btulloh** [comment]
Hi.

I don't see my paper submission on the RWOT github.

I'm new to Github so perhaps I did something wrong.

Please let me know what I should do to correct this issue, thanks.

Bill

**Comment by shannona** [comment]
There were a couple of naming problems. You'd submitted to the main directory instead of the topics-and-advance-reading directory and the name you liked had underscores while the actual filename did not. I've fixed them both.

**Comment by btulloh** [comment]
thanks

**Comment by btulloh** [comment]
Do I need a promotion code for registering for the event?

Thanks

**Comment by ChristopherA** [comment]
You need to contact Joe Andrieu joe@legreq.com for discount codes.

**Comment by btulloh** [comment]
You have been invited to the following event.

Title: Brian at PyCon in Cleveland
When: Thu May 2 – Mon May 6, 2019
Joining info: meet.google.com/ruw-abra-utg  
<https://meet.google.com/ruw-abra-utg>
Or dial: +1 318-431-0450  PIN: 261613624#
Calendar:  
reply@reply.github.com
Who:
     * warner@agoric.com - creator
     * WebOfTrustInfo/rwot8-barcelona

Event details:  
https://www.google.com/calendar/event?action=VIEW&eid=Xzcwb2pnaGkyNjBwNDZiOW02b3EzOGI5azYxMzM2YmExNjUxajZiOWo3MTBrMmgxajhjczQ2ZHBrOGsgcmVwbHkrMDFjZmQ0ZTJjZDM2YjVkMDBmZTIyYzg1ZGQ5NGU3YTJiYjAwYTU4YjVlYTM3MDA4OTJjZjAwMDAwMDAxMTg4OTQyZGE5MmExNjljZTE4YTgwZjMxQHJlcGx5LmdpdGh1Yi5jb20&tok=NzEjYWdvcmljLXN5c3RlbXMuY29tX2tlNTc3Zm42NjNqOGt2YWpybjJmMXJzaHFnQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb21mNTYyOGMwMDdmMWJlZGM3NTIzNzg2MTVhZjQ0MDk3ZmNiM2IwOGJj&ctz=America%2FLos_Angeles&hl=en&es=0

Invitation from Google Calendar: https://www.google.com/calendar/

You are receiving this courtesy email at the account  
reply@reply.github.com  
because you are an attendee of this event.

To stop receiving future updates for this event, decline this event.  
Alternatively you can sign up for a Google account at  
https://www.google.com/calendar/ and control your notification settings for  
your entire calendar.

Forwarding this invitation could allow any recipient to send a response to  
the organizer and be added to the guest list, or invite others regardless  
of their own invitation status, or to modify your RSVP. Learn more at  
https://support.google.com/calendar/answer/37135#forwarding

**Pull request merged**
